{% set version = "0.9.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-listenv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/listenv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/listenv/listenv_{{ version }}.tar.gz
  sha256: 422aaf487b91c6512b83c05536f8dac255db79b16ee85254acc59a3fda8c1c3b

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('listenv')"           # [not win]
    - "\"%R%\" -e \"library('listenv')\""  # [win]

about:
  home: https://github.com/HenrikBengtsson/listenv
  license: LGPL-2.1-or-later
  summary: List environments are environments that have list-like properties.  For instance, the elements of a list environment are ordered and can be accessed and iterated over using index subsetting, e.g. 'x <- listenv(a = 1, b = 2); for (i in seq_along(x)) x[[i]] <- x[[i]] ^ 2; y <- as.list(x)'.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: listenv
# Version: 0.8.0
# Depends: R (>= 3.1.2)
# Suggests: R.utils, R.rsp, markdown
# VignetteBuilder: R.rsp
# Title: Environments Behaving (Almost) as Lists
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Description: List environments are environments that have list-like properties.  For instance, the elements of a list environment are ordered and can be accessed and iterated over using index subsetting, e.g. 'x <- listenv(a = 1, b = 2); for (i in seq_along(x)) x[[i]] <- x[[i]] ^ 2; y <- as.list(x)'.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/listenv
# BugReports: https://github.com/HenrikBengtsson/listenv/issues
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2019-12-05 19:44:24 UTC; hb
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Repository: CRAN
# Date/Publication: 2019-12-05 21:40:02 UTC
